# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('sexe', models.CharField(max_length=1, null=True)),
                ('date_naissance', models.DateField(null=True)),
                ('pere', models.CharField(max_length=20, null=True)),
                ('mere', models.CharField(max_length=20, null=True)),
                ('jumeau', models.NullBooleanField()),
                ('pays', models.CharField(max_length=255, null=True)),
                ('date_insertion', models.DateField(null=True)),
                ('ordre', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cheptel',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('detenteur', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genotypage',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('plaque', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=3)),
                ('format_puce', models.CharField(max_length=20, null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_scan', models.DateField(null=True)),
                ('callrate', models.FloatField(null=True)),
                ('link_to_file', models.CharField(max_length=4096, null=True)),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prelevement',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('plaque', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=3)),
                ('date_enregistrement', models.DateField(null=True)),
                ('date_demande', models.DateField(null=True)),
                ('date_extraction', models.DateField(null=True)),
                ('date_reception_lille', models.DateField(null=True)),
                ('type_materiel', models.CharField(max_length=20, null=True)),
                ('dosage', models.FloatField(null=True)),
                ('conformite_dosage', models.NullBooleanField()),
                ('code_barre', models.CharField(max_length=10, null=True)),
                ('nombre_extraction', models.IntegerField(null=True)),
                ('echec_extraction', models.CharField(max_length=255, null=True)),
                ('statut_vcg', models.CharField(max_length=2, null=True)),
                ('date_insertion', models.DateField(null=True)),
                ('to_html', models.CharField(max_length=4999, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Preleveur',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='prelevement',
            name='preleveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Preleveur'),
        ),
        migrations.AddField(
            model_name='genotypage',
            name='prelevement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Prelevement'),
        ),
        migrations.AddField(
            model_name='animal',
            name='cheptel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Cheptel'),
        ),
        migrations.AddField(
            model_name='animal',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Race'),
        ),
        migrations.AlterUniqueTogether(
            name='prelevement',
            unique_together=set([('plaque', 'position')]),
        ),
        migrations.AlterUniqueTogether(
            name='genotypage',
            unique_together=set([('plaque', 'position')]),
        ),
    ]
