# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('numero', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
                ('sexe', models.CharField(max_length=1, null=True)),
                ('date_naissance', models.DateField(null=True)),
                ('pere', models.CharField(max_length=12, null=True)),
                ('mere', models.CharField(max_length=12, null=True)),
                ('jumeau', models.NullBooleanField()),
                ('pays', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cheptel',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('detenteur', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preleveur',
            fields=[
                ('indentifier', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='cheptel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Cheptel'),
        ),
        migrations.AddField(
            model_name='animal',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Race'),
        ),
    ]
