# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prelevement',
            fields=[
                ('plaque', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=3)),
                ('date_enregistrement', models.DateField(null=True)),
                ('date_demande', models.DateField(null=True)),
                ('date_extraction', models.DateField(null=True)),
                ('date_reception_lille', models.DateField(null=True)),
                ('type_materiel', models.CharField(max_length=20, null=True)),
                ('dosage', models.FloatField()),
                ('conformite_dosage', models.NullBooleanField()),
                ('code_barre', models.CharField(max_length=10, null=True)),
                ('nombre_extraction', models.IntegerField()),
                ('echec_extration', models.CharField(max_length=255, null=True)),
                ('statut_vcg', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
