# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genotypage',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('plaque', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=3)),
                ('format_puce', models.CharField(max_length=20)),
                ('date_debut', models.DateField(null=True)),
                ('date_scan', models.DateField(null=True)),
                ('callrate', models.FloatField(null=True)),
                ('link_to_file', models.CharField(max_length=4096, null=True)),
                ('note', models.TextField(null=True)),
                ('prelevement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Prelevement')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='genotypage',
            unique_together=set([('plaque', 'position')]),
        ),
    ]
