# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_prelevement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelevement',
            name='dosage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='nombre_extraction',
            field=models.IntegerField(null=True),
        ),
    ]
