# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20170419_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelevement',
            name='position',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
