# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20170515_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelevement',
            name='to_html',
            field=models.CharField(max_length=4999, null=True),
        ),
    ]
