# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20170419_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelevement',
            name='animal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form.Animal'),
            preserve_default=False,
        ),
    ]
