# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_prelevement_animal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preleveur',
            old_name='indentifier',
            new_name='numeroagrement',
        ),
        migrations.AddField(
            model_name='animal',
            name='date_insertion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='ordre',
            field=models.IntegerField(null=True),
        ),
    ]
