# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20170424_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='ordre',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
